### ISSUE TITLE
Respect comments

### ISSUE THREAD

**Issue by segeljakt** [saifulapm/chartoggle.nvim#1]
It would be awesome if it was possible to toggle characters before comments. For example:
```lua
{ "hello/world" } -- my comment
```
would toggle:
```lua
{ "hello/world" }, -- my comment
```
Right now it does:
```lua
{ "hello/world" } -- my comment,
```

**Comment by saifulapm** [comment]
I think that is great idea. Thanks

**Comment by saifulapm** [comment]
#[f70db7e](https://github.com/saifulapm/chartoggle.nvim/commit/f70db7e1bd7a2565560cdda60a717ad5fa2241be) This added this feature.
